import type { Metadata } from "next";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme appearance="dark">
        <Navbar/>
          <div className="content">{children}</div>
        </Theme>
      </body>
    </html>
  );
}
